const HOSTURL = 'mongodb://localhost';
const DBNAME = 'SyncDB3'
const MASTERS_ARR = [
    'addressProofMaster',
    'ageProofMaster',
    'appointeeRelationMaster',
    'banksMaster',
    'basePlanDecisionMaster',
    'BIProductMaster',
    'causeOfDeathMaster',
    'channelProductMapping',
    'chequeTypeMaster',
    'cityMaster',
    'comboCauseOfDeathMaster',
    'countryMaster',
    'cvdDeclinedReason',
    'cvdPrevPolicyProductCiteria',
    'eduMaster',
    'eNachBankMapping',
    'familyRelationMaster',
    'healthInsuranceCompaniesMaster',
    'healthStatusMaster',
    'identityProofMaster',
    'incomeProofMaster',
    'insuranceCompaniesMaster',
    'irMasterNew',
    'maritalStatusMaster',
    'nationalityMaster',
    'natureOfDutiesMaster',
    'nomineeRelationMaster',
    'occupationMaster',
    'orgMaster',
    'paramilitarySubSection',
    'passwordRuleMaster',
    'payerRelationMaster',
    'pincodeMaster',
    'productFeatureMaster',
    'productMaster',
    'proposerRelationMaster',
    'qualificationMaster',
    'residentialStatusMaster',
    'stateMaster',
    'wealthcauseOfDeathMaster'
];
module.exports = {
    HOSTURL,
    DBNAME,
    MASTERS_ARR
}

